### ISSUE TITLE
Marquee Tag Unsupported on Mobile

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pattern-library#5]
CHROME: Version 43.0.2357.124 (64-bit)
MACOSX: 10.9.4 BUILD 13E28

Text is improperly cut off:

![screen shot 2015-06-18 at 5 05 55 pm](https://cloud.githubusercontent.com/assets/1957344/8244941/57be0c96-15dc-11e5-8fc6-717b7cb6b97d.png)

**Comment by davidrleonard** [comment]
Tough break. Don't think this is in the scope for how we want to improve the pattern library going forward.
